version: '3.8'

services:
  weather-api:
   image: bishalhaldar/weather-api
   container_name: weather-api
   ports:
    - "3000:3000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.y